stages:
  - build
  - deploy

image: java:8-jdk # jdk8 도커 이미지 사용 (배포환경에 따라 변경할 것)

cache:
  paths: # .gradle 캐시 적용
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  before_script:
    - chmod +x ./gradlew # gradlew 실행권한 부여 (초기 권한 666 [-rw-rw-rw-])
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar	# build의 결과물인 jar파일을 artifacts로 지정.
    expire_in: 1 week	# 1주일 동안  보관

deploy-to-server:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s) # ssh-agent 백그라운드 실행

    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    - chmod 600 "$SSH_KEY" # 개인키 파일 권한변경
    - ssh-add "$SSH_KEY"   # SSH 개인키 추가
  script:
    # SSH를 이용한 원격 파일 업로드
    - scp build/libs/*.jar 계정명@"$DEPLOY_SERVER_IP":~/BUILD_PATH/build.jar
    # 원격 스크립트 실행